config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  root to: 'static#home'

  get 'static/home'
  resources :shops do
    resources :items
  end

  resources :items, except: [:index]
  get '/auth/facebook/callback' => 'sessions#create'

  resources :users

  resources :shops
  resources :categories

  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/signup', to: "users#new", as: "signup"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :shop
  before_destroy :has_references?

  scope :order_by_quantity, -> { order(quantity: :desc).limit(5) }

  def self.order_by_units
    order(quantity: :desc)
  end

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 300 }
  validates :sku, presence: true, uniqueness: true, numericality: { ony_integer: true }
  validates :quantity, presence: true, numericality: { only_integer: true }
  validates :price, presence: true, numericality: true

  has_many :line_items
  has_many :item_categories
  has_many :categories, through: :item_categories
  #accepts_nested_attributes_for :categories

  def category_name=(name)
     self.categories.first = Category.find_or_create_by(name: name)
   end

   def category_name
      self.categories.first ? self.categories.first.name : nil
   end

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      category = Category.find_or_create_by(category_attribute)
      self.categories << category if category
    end
  end

  private

  def has_references?
    unless line_items.empty?
      errors.add(:base, "Line Items Present")
      throw :abort
    end
  end

end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :items

  #scope :order_by_quantity, -> { joins(:items).order(quantity: :desc).limit(5) }
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  include CurrentCart
  before_action :set_cart

  def index
    @shops = Shop.all
  end

  def show
    @items = @shop.items.order_by_quantity
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.valid?
      @shop.save
      redirect_to shop_path(@shop)
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:name)
  end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<div align="center">
  <%= form_for @shop do |f| %>
    <% if @shop.errors.any? %>
      <div>
        <h2>
          <%= pluralize(@shop.errors.count, "error") %> prohibited
          this shop from saving:
        </h2>
        <ul>
          <% @shop.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/shops/edit.html.erb
<h1 align="center">Edit Your Shop</h1>

<%= render 'form' %>

app/views/shops/index.html.erb
<div align="center">
  <h1>Browse Our Shops</h1>
  <% @shops.each do |shop| %>
    <p><%= link_to shop.name, shop_path(shop) %> | <%= link_to "Edit Shop", edit_shop_path(shop) %> | <%= link_to "Delete Shop", shop_path(shop), method: :delete, data: { confirm: "Are You Sure?" } %></p>
  <% end %>

  <%= link_to "Create New Shop", new_shop_path, class: "btn btn-primary" %>
</div>

app/views/shops/new.html.erb
<h1 align="center">Create A New Shop</h1>

<%= render 'form' %>

app/views/shops/show.html.erb
<div align="center">
  <h2>Shop Details</h2>

  <p><%= @shop.name.capitalize %> | <%= link_to "All Items", shop_items_path(@shop, @item) %> | <%= link_to "Create New Item", new_shop_item_path(@shop) %></p>

  <h3>Most Available Products</h3>

  <% if !@shop.items.empty? %>
    <ul>
        <% @items.each do |item| %>
          <li><%= item.name %>: <%= item.quantity %> units</li>
        <% end %>
        <%= link_to "All (#{@shop.items.size}) Products", shop_items_path(@shop)  %> 
    </ul>
  <% end %>

<!-- form for creating a new item
 item is only created through a store.
 item does not exist without store
 item must have a category, which the user can
 pick from a dropdown menu, or create if none apply -->

  <h4>Add Item To Shop</h4>

  <%= form_for [@shop, @shop.items.build] do |f| %>

    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </p>
    <p>
      <%= f.label :sku %>
      <%= f.text_field :sku %>
    </p>
    <p>
      <%= f.label :image %>
      <%= f.text_field :image %>
    <p>
    <p>
      <%= f.label :quantity %>
      <%= f.text_field :quantity %>
    <p>
    <p>
      <%= f.label :price %>
      <%= f.text_field :price %>
    </p>

    <p><%= f.collection_check_boxes :category_ids, Category.all, :id, :name %></p>

    <p>
      <%= f.label :category_name %>
      <%= f.text_field :category_name %>
    </p>
    <%= f.submit %>
  <% end %>

  <%= link_to "All Shops", shops_path, class: "btn btn-primary" %>
</div>