config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  root to: 'static#home'

  get 'static/home'
  resources :shops do
    resources :items
  end

  resources :items, except: [:index]
  get '/auth/facebook/callback' => 'sessions#create'

  resources :users

  resources :shops
  resources :categories

  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/signup', to: "users#new", as: "signup"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  #belongs_to :user
  has_many :line_items, dependent: :destroy

  def add_item(item)
    current_item = line_items.find_by(item_id: item.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(item_id: item.id)
    end
    current_item
  end

  def total_checkout_price
    sum = 0
    #call to_a on self.line_items because self.line_items return a relation, not an array
    self.line_items.to_a.each do |item|
      sum += item.total_price
    end
    sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :item_categories
  has_many :items, through: :item_categories

  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :shop
  before_destroy :has_references?

  scope :order_by_quantity, -> { order(quantity: :desc).limit(5) }

  def self.order_by_units
    order(quantity: :desc)
  end

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 300 }
  validates :sku, presence: true, uniqueness: true, numericality: { ony_integer: true }
  validates :quantity, presence: true, numericality: { only_integer: true }
  validates :price, presence: true, numericality: true

  has_many :line_items
  has_many :item_categories
  has_many :categories, through: :item_categories
  #accepts_nested_attributes_for :categories

  def category_name=(name)
     self.categories.first = Category.find_or_create_by(name: name)
   end

   def category_name
      self.categories.first ? self.categories.first.name : nil
   end

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      category = Category.find_or_create_by(category_attribute)
      self.categories << category if category
    end
  end

  private

  def has_references?
    unless line_items.empty?
      errors.add(:base, "Line Items Present")
      throw :abort
    end
  end

end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def total_price
    item.price * quantity
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :items

  #scope :order_by_quantity, -> { joins(:items).order(quantity: :desc).limit(5) }
end

app/models/user.rb
class User < ApplicationRecord
  #has_one :cart, dependent: :destroy
  validates :name, presence: true
  validates :password, presence: true, length: { minimum: 8 }
  EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: EMAIL_REGEX, message: "Email must be properly formatted" }

  has_secure_password

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = SecureRandom.hex
    end
  end
end

=begin
def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end
=end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        redirect_to @cart
      else
        render :new
      end
    end
  end

  def destroy
    @cart.destroy
    session[:cart_id] = nil
    redirect_to shops_path
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def invalid_cart
      logger.error "Attempted to access an invalid cart #{params[:id] }"
      redirect_to root_path
    end

    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include CurrentCart
  before_action :set_item, only: [:edit, :update, :destroy]
  before_action :set_cart

  def index
      @shop = Shop.find(params[:shop_id])
      @items = @shop.items.order_by_units
  end

  def show
    #@shop = Shop.find(params[:shop_id])
    @item = Item.find(params[:id])
  end

  def new
    @shop = Shop.find(params[:shop_id])
    #@item = Item.new
    @item = @shop.items.build
    # @item = Item.new(shop_id: params[:shop_id]) -- flatiron way
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @item = @shop.items.create(set_params)
    if @item.save
      redirect_to shop_path(@item.shop)
    else
      render :new
    end
  end

  def edit

  end



  def update
    if @item.update(set_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  def order_by_units
    @shop = Shop.find(params[:shop_id])
    @items = @shop.items.order_by_units
  end

  private

  def set_params
    params.require(:item).permit(:name, :description, :image, :quantity, :price, :sku, category_ids: [])
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  include CurrentCart
  before_action :set_cart

  def index
    @shops = Shop.all
  end

  def show
    @items = @shop.items.order_by_quantity
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.valid?
      @shop.save
      redirect_to shop_path(@shop)
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "DigitalSquare", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "All Stores", shops_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

      <li class="nav-item">
        <%= link_to "All Categories", categories_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Log Out", logout_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", login_path, class: "nav-link" %>
          <%= link_to('Log in with Facebook!', '/auth/facebook') %>
        </li>
      <% end %>
      <% if logged_in? %>
        <li class="nav-item">
          Logged in as:  <%= link_to current_user.name, user_path(current_user) %> | <%= link_to "Log Out", logout_path %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", signup_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Users", users_path %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Find A Store</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/nav' %>

    <%= yield %>

    <div id="sidebar">
      <div id="cart">
        <%= render @cart if @cart && logged_in? %>
      </div>
    </div>
  </body>
</html>